/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.57
 * Generated at: 2015-02-15 18:54:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Consos Cafés</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <!-- téléchargement de JQuery sur MaxCDN -->\n");
      out.write("        <script src=\"//code.jquery.com/jquery-2.1.3.min.js\"></script>\n");
      out.write("        <!-- scripts et css pour jqueryui -->\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"scripts/jqueryui/jquery-ui.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"scripts/jqueryui/jquery-ui.structure.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"scripts/jqueryui/jquery-ui.theme.min.css\">\n");
      out.write("        <script src=\"scripts/jqueryui/jquery-ui.min.js\"></script>\n");
      out.write("        <link href=\"scripts/jqueryui/jquery.dynatable.css\" rel=\"stylesheet\" type=\"text/css\"/>\n");
      out.write("        <script src=\"scripts/jqueryui/jquery.dynatable.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"styles/cafe.css\">\n");
      out.write("        <script src=\"scripts/consoscafe.js\"></script>\n");
      out.write("       <script src=\"//cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js\"></script>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"//cdn.datatables.net/1.10.5/css/jquery.dataTables.min.css\">\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div id='wrapper'>\n");
      out.write("            <header>\n");
      out.write("                <p id=\"header\"><img src=\"images/coffeeSmall.png\"/> Consommations des cafés</p>\n");
      out.write("            </header>\n");
      out.write("            <div id=\"tabs\">\n");
      out.write("                <ul>\n");
      out.write("                    <li><a href=\"#tabs-1\">Par semaine</a></li>\n");
      out.write("                    <li><a href=\"#tabs-2\">Par programmeur</a></li>\n");
      out.write("                    <li><a href=\"#tabs-3\">Par bureau</a></li>\n");
      out.write("                </ul>\n");
      out.write("                <div id=\"tabs-1\">\n");
      out.write("                    <h1>Consommations hebdomadaires des cafés</h1>\n");
      out.write("                    <form id=\"semainesForm\">\n");
      out.write("                        <label for=\"numSemInput\">semaine:&nbsp;</label>\n");
      out.write("                        <input id=\"numSemInput\" type=\"week\" \n");
      out.write("                               name=\"numSem\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.numSem}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('"');
      out.write('>');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageErreur}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                        <input type=\"hidden\" name=\"format\" value=\"HTML\" checked/>\n");
      out.write("                    </form>\n");
      out.write("                    <br><br>\n");
      out.write("                    <div id=\"tabConsosSemaine\"></div>\n");
      out.write("                    <p id=\"pdfConsosSemaine\">télécharger la table en pdf \n");
      out.write("                        <a href=\"#\" download><img src=\"images/pdf_icon_32.png\"></a>\n");
      out.write("                        <!-- attribut download ne semble pas être supporté par IE et Safari\n");
      out.write("                             voir http://caniuse.com/#feat=download\n");
      out.write("                             le remplacer par target=\"_blank\" -->\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"tabs-2\">\n");
      out.write("                    <h1>Consommations hebdomadaires des cafés</h1>\n");
      out.write("                    <form id=\"programmeurForm\">\n");
      out.write("                        <label for=\"idProg\">ID Programmeur:&nbsp;</label>\n");
      out.write("                        <input id=\"idProg\" type=\"number\" \n");
      out.write("                               name=\"idProg\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageErreur}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                        <input type=\"hidden\" name=\"format\" value=\"HTML\" checked/>\n");
      out.write("                    </form>\n");
      out.write("                    <br><br>\n");
      out.write("                    <div id=\"tabConsosProgrammeur\"></div>\n");
      out.write("                    <p id=\"pdfConsosProgrammeur\">télécharger la table en pdf \n");
      out.write("                        <a href=\"#\" download><img src=\"images/pdf_icon_32.png\"></a>\n");
      out.write("                        <!-- attribut download ne semble pas être supporté par IE et Safari\n");
      out.write("                             voir http://caniuse.com/#feat=download\n");
      out.write("                             le remplacer par target=\"_blank\" -->\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("                <div id=\"tabs-3\">\n");
      out.write("                    <h1>Consommations hebdomadaires des cafés par Bureau</h1>\n");
      out.write("                    <form id=\"bureauForm\">\n");
      out.write("                        <label for=\"numBureau\">Numero de bureau:&nbsp;</label>\n");
      out.write("                        <input id=\"numBureau\" type=\"number\" \n");
      out.write("                               name=\"numBureau\"> ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${messageErreur}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\n");
      out.write("                        <input type=\"hidden\" name=\"format\" value=\"HTML\" checked/>\n");
      out.write("                    </form>\n");
      out.write("                    <br><br>\n");
      out.write("                    <div id=\"tabConsosBureau\">\n");
      out.write("                        <table id=\"MyTableDyna\">\n");
      out.write("                            <thead>\n");
      out.write("                            <th>NO_SEMAINE</th>\n");
      out.write("                            <th>NB_TASSES</th>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <p id=\"pdfConsosBureau\">télécharger la table en pdf \n");
      out.write("                        <a href=\"#\" download><img src=\"images/pdf_icon_32.png\"></a>\n");
      out.write("                        <!-- attribut download ne semble pas être supporté par IE et Safari\n");
      out.write("                             voir http://caniuse.com/#feat=download\n");
      out.write("                             le remplacer par target=\"_blank\" -->\n");
      out.write("                    </p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
