
DROP TABLE INIEPREUVES;
DROP TABLE INIINSCRIPTIONSEQUIPES;
DROP TABLE INIINSCRIPTIONSSPORTIFS;
DROP TABLE INILOGEMENTSINIT;
DROP TABLE INIRESULTATSEQUIPES;
DROP TABLE INIRESULTATSSPORTIFS;
DROP TABLE INISPORTIFS;
DROP TABLE INISPORTIFSEQ;

/*
DROP TABLE LesDisciplines;
DROP TABLE LesEpreuves;
DROP TABLE LesEpreuvesIndividuelles;
DROP TABLE LesEpreuvesParEquipe;
DROP TABLE LesBatiments;
DROP TABLE LesChambres;
DROP TABLE LesDelegations;
DROP TABLE LesParticipants;
DROP TABLE LesSportifs;
DROP TABLE LesConstitutionsEQUIPES;
DROP TABLE LesEquipes;
DROP TABLE LesMedailles;
DROP TABLE LesParticipations;


