DROP TABLE INIEPREUVES;
DROP TABLE INIINSCRIPTIONSEQUIPES;
DROP TABLE INIINSCRIPTIONSSPORTIFS;
DROP TABLE INILOGEMENTSINIT;
DROP TABLE INIRESULTATSEQUIPES;
DROP TABLE INIRESULTATSSPORTIFS;
DROP TABLE INISPORTIFS;
DROP TABLE INISPORTIFSEQ;

