CREATE TABLE INIEPREUVES (NEPREUVE NUMBER(3), NOME VARCHAR2(20), FORME VARCHAR2(12), DISCIPLINE VARCHAR2(25), CATEGORIE VARCHAR2(10), NBS NUMBER(2), DATEEPR DATE);
Insert into iniepreuve
    select * from jo.lesepreuves;

CREATE TABLE INIINSCRIPTIONSEQUIPES (NI NUMBER(4), NEPREUVE NUMBER(3));
Insert into iniinscriptionsequipes
    select * from jo.lesinscriptionequipes;

CREATE TABLE INIINSCRIPTIONSSPORTIFS (NOM VARCHAR2(20), PRENOM VARCHAR2(20), PAYS VARCHAR2(20), CATEGORIE VARCHAR2(20), DATENAIS DATE, NEPREUVE NUMBER(3));
Insert into iniinscriptionssportifs
    select * from jo.lesinscriptionssportifs;

CREATE TABLE LESLOGEMENTSINIT (NLOGEMENT NUMBER(3), CAPACITE NUMBER(2), NOM VARCHAR2(20), PRENOM VARCHAR2(20), NOMBAT VARCHAR2(20), NUMERO NUMBER(4), RUE VARCHAR2(20), VILLE VARCHAR2(20));
Insert into inilogementsinit
    select * from jo.leslogementsinit;

CREATE TABLE LESRESULTATSEQUIPES (NEPREUVE NUMBER(2), GOLD NUMBER(4), SILVER NUMBER(4), BRONZE NUMBER(4));
Insert into iniresultatsequipes
    select * from jo.lesresultatsequipes;

CREATE TABLE LESRESULTATSSPORTIFS (NEPREUVE NUMBER(2), NOMOR VARCHAR2(20), PRENOMOR VARCHAR2(20), NOMAR VARCHAR2(20), PRENOMAR VARCHAR2(20), NOMBR VARCHAR2(20), PRENOMBR VARCHAR2(20));
Insert into iniresultatssportifs
    select * from jo.lesresultatssportifs;

CREATE TABLE LESSPORTIFS (NS NUMBER(4), NOM VARCHAR2(20), PRENOM VARCHAR2(20), PAYS VARCHAR2(20), CATEGORIE VARCHAR2(10), DATENAIS DATE);
Insert into inisportifs
    select * from jo.lessportifs;

CREATE TABLE LESSPORTIFSEQ (NOM VARCHAR2(20), PRENOM VARCHAR2(20), PAYS VARCHAR2(20), CATEGORIE VARCHAR2(10), DATENAIS DATE, NEQUIPE NUMBER(2));
Insert into inisportifseq
    select * from jo.lessportifseq;


